from ipywidgets import interact, interactive
import ipywidgets as widgets
import IPython
from IPython.display import display
from IPython.display import clear_output
import datetime

import pandas as pd
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_rows', 200)
import numpy as np
import matplotlib.pyplot as plt
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot
init_notebook_mode(connected = True)
import seaborn as sns
import plotly.graph_objects as go